server:
  port: 10008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#oracle数据库
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//10.1.195.102:1521/AIDB
    username: aialm2
    password: aialm2
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true

logback:
  loglevel: DEBUG