server:
  port: 8761
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:${user.dir}/config-repo
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/