server:
  port: 8761

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:${user.dir}/config-repo
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

